In [1]:
import pandas as pd

df = pd.read_excel("Flight_Fare.xlsx")

df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [3]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [4]:
df.shape

(10683, 11)

In [5]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [7]:
df["Date_of_Journey"] = pd.to_datetime(df["Date_of_Journey"], dayfirst=True)

In [8]:
df["Journey_day"] = df["Date_of_Journey"].dt.day
df["Journey_month"] = df["Date_of_Journey"].dt.month

In [13]:
df["Dep_hour"] = pd.to_datetime(df["Dep_Time"], errors='coerce', format='mixed').dt.hour
df["Dep_min"] = pd.to_datetime(df["Dep_Time"], errors='coerce', format='mixed').dt.minute

df["Arrival_hour"] = pd.to_datetime(df["Arrival_Time"], errors='coerce', format='mixed').dt.hour
df["Arrival_min"] = pd.to_datetime(df["Arrival_Time"], errors='coerce', format='mixed').dt.minute

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le = LabelEncoder()

In [16]:
df["Airline"] = le.fit_transform(df["Airline"])
df["Source"] = le.fit_transform(df["Source"])
df["Destination"] = le.fit_transform(df["Destination"])

In [17]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Journey_day,Journey_month,Dep_hour,Dep_min,Arrival_hour,Arrival_min
0,3,2019-03-24,0,5,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,22,20,1,10
1,1,2019-05-01,3,0,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,5,50,13,15
2,4,2019-06-09,2,1,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,9,25,4,25
3,3,2019-05-12,3,0,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,18,5,23,30
4,3,2019-03-01,0,5,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,16,50,21,35

In [18]:
df.drop(["Date_of_Journey", "Dep_Time", "Arrival_Time", "Route", "Additional_Info"], axis=1, inplace=True)

In [19]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Price,Journey_day,Journey_month,Dep_hour,Dep_min,Arrival_hour,Arrival_min
0,3,0,5,2h 50m,non-stop,3897,24,3,22,20,1,10
1,1,3,0,7h 25m,2 stops,7662,1,5,5,50,13,15
2,4,2,1,19h,2 stops,13882,9,6,9,25,4,25
3,3,3,0,5h 25m,1 stop,6218,12,5,18,5,23,30
4,3,0,5,4h 45m,1 stop,13302,1,3,16,50,21,35

In [22]:
df["Duration"] = df["Duration"].astype(str)

df["Duration"] = df["Duration"].str.replace("h", "*60").str.replace(" ", "+").str.replace("m", "*1")

df["Duration"] = df["Duration"].apply(eval)

In [23]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Price,Journey_day,Journey_month,Dep_hour,Dep_min,Arrival_hour,Arrival_min
0,3,0,5,170,non-stop,3897,24,3,22,20,1,10
1,1,3,0,445,2 stops,7662,1,5,5,50,13,15
2,4,2,1,1140,2 stops,13882,9,6,9,25,4,25
3,3,3,0,325,1 stop,6218,12,5,18,5,23,30
4,3,0,5,285,1 stop,13302,1,3,16,50,21,35

In [24]:
df["Total_Stops"] = df["Total_Stops"].map({
    "non-stop": 0,
    "1 stop": 1,
    "2 stops": 2,
    "3 stops": 3,
    "4 stops": 4
})

In [25]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Price,Journey_day,Journey_month,Dep_hour,Dep_min,Arrival_hour,Arrival_min
0,3,0,5,170,0.0,3897,24,3,22,20,1,10
1,1,3,0,445,2.0,7662,1,5,5,50,13,15
2,4,2,1,1140,2.0,13882,9,6,9,25,4,25
3,3,3,0,325,1.0,6218,12,5,18,5,23,30
4,3,0,5,285,1.0,13302,1,3,16,50,21,35

In [27]:
df["Total_Stops"] = df["Total_Stops"].fillna(0)
df["Total_Stops"] = df["Total_Stops"].astype(int)

In [28]:
df["Total_Stops"].unique()

array([0, 2, 1, 3, 4])

In [29]:
from sklearn.model_selection import train_test_split

X = df.drop("Price", axis=1)
y = df["Price"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

RandomForestRegressor()

In [31]:
y_pred = model.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.795227639292247

In [32]:
model = RandomForestRegressor(n_estimators=200, max_depth=10)

In [34]:
model = RandomForestRegressor(n_estimators=200, max_depth=10)

model.fit(X_train, y_train)   # 🔥 YOU MISSED THIS

import pandas as pd
feature_importance = pd.Series(model.feature_importances_, index=X.columns)
feature_importance.sort_values(ascending=False)

Duration         0.517892
Journey_day      0.138991
Airline          0.109173
Total_Stops      0.054398
Journey_month    0.048190
Destination      0.034950
Arrival_hour     0.028067
Dep_hour         0.024155
Dep_min          0.020184
Arrival_min      0.017354
Source           0.006646
dtype: float64